# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-19 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PandCriteria',
            new_name='PandPandDetail',
        ),
    ]
